- name: nginx install & start services
  hosts: linux
  become: true
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: Enable service nginx, and not touch the state
    service:
      name: nginx
      enabled: yes
  