- hosts: servers
  become: true
  tasks:
  - name: Upgrade all packages for RedHat instances
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Upgrade all packages for Debian instances
    apt:
      name: '*'
      state: latest
    when: ansible_os_family == "Debian"