---
- hosts: servers
  become: yes
  tasks:
  - name: Start and enable httpd service
    service:
      name: httpd  
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: Start and enable apache2 service
    service:
      name: apache2 
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
