---
- hosts: servers
  become: yes
  tasks:
  - name: Add a line to a file if the file does not exist, without passing regexp
	  lineinfile:
	  path: /etc/resolv.conf
	  line: 192.168.1.99 foo.lab.net foo
	  create: yes