---
- hosts: servers
  become: yes
  tasks:
  - name: Create a new primary partition
    parted:
      device: /dev/sdc
      number: 1
      state: present

  - name: Remove partition number 1
    parted:
      device: /dev/sdc
      number: 1
      state: absent

  - name: Create a new primary partition with a size of 1GiB
    parted:
      device: /dev/sdc
      number: 1
      state: present
      part_end: 1GiB

  - name: Create a new primary partition for LVM
    parted:
      device: /dev/sdc
      number: 2
      flags: [ lvm ]
      state: present
      part_start: 1GiB

  - name: Remove all partitions from disk
    parted:
      device: /dev/sdc
      number: '{{ item.num }}'
      state: absent
    loop: '{{ sdc_info.partitions }}'

























