- hosts: win
  tasks:
  - name: Install multiple packages sequentially
    win_chocolatey:
      name: '{{ item }}'
      state: present
    loop:
    - firefox
    - curl
    - winscp
    - procexp
    - putty
    - windirstat