- hosts: win
  tasks:
  - name: Uninstall multiple packages
    win_chocolatey:
      name: '{{ item }}'
      state: absent
    loop:
    - firefox
    - curl
    - winscp
    - procexp
    - putty
    - windirstat