- name: demonstrate changed status
  hosts: linux
  become: yes
  tasks:
  - name: check local time
    command: date
    register: command_result
    changed_when: false

  - name: print local time
    debug:
      var: command_result.stdout