- name: set up web server
  hosts: linux
  become: true
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest
    - name: copy index.html
      copy:
        src: /tml/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: copy nothing - intended to fail
      copy:
        src: /tmp/nothing
        dest: /var/www/html/nothing.html
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted