- name: test register
  hosts: linux
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug: 
        msg: echo "passwd contains user lisa"
      when: passwd_contents.stdout.find('lisa') != -1