- hosts: servers
  become: true
  tasks:
  - name: Update all packages to the latest version for Debian instances
    apt:
      upgrade: dist
    when: ansible_os_family == "Debian"

  - name: Update all packages to the latest version for	RedHat instances
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"