- name: simple block example
  hosts: linux
  become: yes
  gather_facts: yes
  tasks:
    - name: setting up http
      block:
      - name: installing http
        yum:
          name: httpd
          state: present
      - name: restart httpd
        service:
          name: httpd
          state: started
      when: ansible_distribution == "RedHat"
