- hosts: servers
  become: yes
  tasks:
  - name: Stop httpd service
    service:
      name: httpd  
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Stop apache2 service
    service:
      name: apache2 
      state: stopped
    when: ansible_os_family == "Debian"