- hosts: servers
  become: yes
  tasks:
  - name: checking httpd service status
    command: systemctl status httpd
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result
    when: ansible_os_family == "RedHat"

  - name: checking apache2 service status
    command: systemctl status apache2.service
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result
    when: ansible_os_family == "Debian"