- name: deploy vsftpd
  hosts: linux
  become: true
  tasks:
  - name: install vsftpd
    yum: 
      name: vsftpd

  - name: enable vsftpd
    service: 
      name: vsftpd 
      enabled: true

  - name: create README file
    copy:
      content: "welcome to this FTP server"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444