- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2: 
      instance_type: t2.micro
      key_name: key-pair
      image: ami-01aab85a5e4a5a0fe
      region: us-east-2
      group: default
      count: 1
      vpc_subnet_id: subnet-9cfa25f7
      wait: yes
      assign_public_ip: yes
